#!/usr/bin/env bash

docker tag $IMAGE_NAME $DOCKER_REPO:namesrv-4.7.1
docker tag $IMAGE_NAME $DOCKER_REPO:rocketmq-namesrv-4.7.1
docker push $DOCKER_REPO:namesrv-4.7.1
docker push $DOCKER_REPO:rocketmq-namesrv-4.7.1
