#!/usr/bin/env bash

docker tag $IMAGE_NAME $DOCKER_REPO:broker
docker tag $IMAGE_NAME $DOCKER_REPO:broker-4.7.1
docker tag $IMAGE_NAME $DOCKER_REPO:rocketmq-broker-4.7.1
docker push $DOCKER_REPO:broker
docker push $DOCKER_REPO:broker-4.7.1
docker push $DOCKER_REPO:rocketmq-broker-4.7.1