version: '3'
services:
  mysql:
    image: chaiyd/mysql:8.0.25
    container_name: wkcrm_mysql
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - wkcrm_network
    ports:
      - "3306:3306"
    restart: always

  redis:
    image: registry.cn-hangzhou.aliyuncs.com/72crm/redis:6.0.8
    container_name: wkcrm_redis
    volumes:
      - ./conf/redis/redis.conf:/etc/redis.conf
    ports:
      - "6379:6379"
    networks:
      - wkcrm_network
    command: [ "redis-server", "/etc/redis.conf" ]
    restart: always

  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/72crm/elasticsearch:6.8.6
    container_name: elasticsearch
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
      - ./data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    environment:
      - discovery.type=single-node
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - "9200:9200"
    networks:
      - wkcrm_network
    restart: always

  nacos:
    image: chaiyd/nacos:2.0.1
    container_name: wkcrm_nacos
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql # nacos 不支持utf8mb4
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=password
    depends_on:
      - mysql
    volumes:
      - ./log/nacos:/home/nacos/logs
    ports:
      - "8848:8848"
    networks:
      - wkcrm_network
    restart: always

  xxl-job-admin:
    image: registry.cn-hangzhou.aliyuncs.com/72crm/xxl-job:2.1.2
    container_name: wkcrm_xxl-job-admin
    volumes:
      - ./log/xxl-job:/data/applogs/xxl-job/
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?Unicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=password'
    ports:
      - "8080:8080"
    networks:
      - wkcrm_network
    depends_on:
      - mysql
      - nacos
      - redis
    restart: always

  nginx:
    image: chaiyd/nginx:1.20.0
    # docker-nginx https://github.com/chaiyd/nginx.git
    container_name: wkcrm_nginx
    ports:
      - "80:80"
    volumes:
      - ./log/nginx/:/etc/nginx/logs/
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/
      #- ./html/static:/etc/nginx/html/static
      #- ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - wkcrm_network
    depends_on:
      - wkcrm
    restart: always

  wkcrm:
    image: registry.cn-hangzhou.aliyuncs.com/72crm/crm:11.3.1
    container_name: wkcrm
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - ./wkcrm.sh:/wkcrm.sh
      - ./log/wkcrm:/opt/package/logs/
      - ./data/wkcrm/file:/opt/upload/
    ports:
      - "8443:8443"
    networks:
      - wkcrm_network
    entrypoint: /wkcrm.sh restart
    depends_on:
      - mysql
      - nacos
      - redis
    restart: always

networks:
  wkcrm_network: